### ISSUE TITLE
[Feat] Basic Mod Management

### ISSUE THREAD

**Issue by john681611** [flying-dice/dcs-dropzone-mod-manager#5]
- [x]  Deal with zips
- [x] Unzip dealing with archive subfolders.
- [x]  Symlinking Dir
- [ ]  Symlinking Single File (Throes EPERM error)
- [x] Progress feedback for each file
- [ ] Cancellation of download & Cleanup 
- [ ] Mod Management
   - [x]  Check if already installed
   - [x]  Check the install version (store file somewhere with the last installed version)
   - [x] Uninstall
   - [x] Toggle on off
   - [x] Update (assumed uninstall then install)
 - [ ] Genric Install method
    - [ ] Github Release Determine the download link using pattern

**Comment by JonathanTurnock** [comment]
Most of this is back, I think the only thing that isnt present that was ticket is

- Update (Right now user just needs to unsubscribe and re-subscribe but probably need to put the notification that an update is present which IIRC was there before?) https://github.com/flying-dice/dcs-dropzone-mod-manager/issues/15

- Cancellation is entirely possible with rclone there's a stop job command just needs to be implemented right now the workaround would be to unsubscribe and restart the app which kills the rclone process. https://github.com/flying-dice/dcs-dropzone-mod-manager/issues/14

Last one is probably something that can belong in the Registry side rather than on the client?

WRT Symlinking single files everything works when its run as admin, seems to be a limitation at present, raised a separate issue:
https://github.com/flying-dice/dcs-dropzone-mod-manager/issues/16

**Comment by JonathanTurnock** [comment]
Shall we close this off in favour of granular issues?
